package:
  name: octant
  version: "0.0.11"

source:
  git_rev: v0.0.11
  git_url: https://github.com/dennissergeev/octant.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - octant

about:
  home: https://github.com/dennissergeev/octant
  license: MIT 
  license_file: LICENSE
