name: octant_docs
channels:
- conda-forge
dependencies:
- python=3.6
- cython
- ipython
- matplotlib
- numpy
- numpydoc
- pandas
- pytest
- pytables
- scipy
- sphinx
- sphinx-gallery
- sphinx_rtd_theme
- xarray
