package:
  name: octant
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/dennissergeev/octant.git

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    - numpy
    - pandas
    - xarray

build:
  script_env:
   - VERSION
   - CONDA_BLD_PATH

test:
  imports:
    - octant
    - numpy

about:
  home: https://github.com/dennissergeev/octant
  license: MIT 
  license_file: LICENSE
